services:
  - type: web
    name: college-event-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false # Setting this to false will prompt you to enter the Neon URL during setup
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: True
